Repository normit581/cits3200-proj, pull requests merged in 2024-08, with the labels that each got.

#13 Issue 12 UI improvement and file upload functionality
  app/__init__.py
  app/config.py
  app/routes.py
  app/static/js/base.js
  app/static/js/home.js
  app/static/styles/base.css
  app/static/styles/home.css
  app/templates/base.html
  app/templates/home.html
  app/templates/layout/footer.html
  app/templates/layout/nav_bar.html
  app/templates/layout/page_not_found.html
  app/templates/team.html
  start.sh
Labels: enhancement, frontend

#19 Implement file input handling, validation, flash messages
  app/config.py
  app/forms.py
  app/routes.py
  app/static/js/base.js
  app/static/js/home.js
  app/static/styles/base.css
  app/static/styles/home.css
  app/templates/home.html
  app/templates/layout/alert_modal.html
  requirements.txt
Labels: enhancement, backend

#30 Add files via upload
  documents/sprint1_deliverables/CITS3200 User Stories.docx
Labels: documentation

#36 Enhance stories and introduce for tester/documenter
  documents/sprint1_deliverables/CITS3200 User Stories.docx
Labels: documentation

#31 Risk register
  documents/sprint1_deliverables/Risk_Register.xlsx
  documents/sprint1_deliverables/Team 11 Risk Register.docx
Labels: documentation

#34 Upload of PAT
  documents/sprint1_deliverables/Team 11 Project Acceptance Tests.docx
Labels: documentation

#38 Scope of work
  documents/sprint1_deliverables/Scope of work.docx
Labels: documentation

#45 Issue 40 visualise route
  app/routes.py
  app/utilities/metadata.py
  app/utilities/rsid.py
Labels: backend

#47 Issue 42 UI for output display after document matching
  app/fields.py
  app/forms.py
  app/routes.py
  app/static/js/base.js
  app/static/js/home.js
  app/static/js/setting-bar.js
  app/static/js/visualise.js
  app/static/styles/base.css
  app/static/styles/home.css
  app/static/styles/visualise.css
  app/templates/home.html
  app/templates/layout/nav_bar.html
  app/templates/layout/page_not_found.html
  app/templates/visualise.html
Labels: enhancement, frontend
