Repository normit581/cits3200-proj, pull requests merged in 2024-10, with the labels that each got.

#130 Issue 115 code refactoring
  app/__init__.py
  app/config.py
  app/fields.py
  app/forms.py
  app/helper.py
  app/processor.py
  app/routes.py
  app/static/img/project-logo.ico
  app/static/js/base.js
  app/static/js/home.js
  app/static/js/visualise.js
  app/static/styles/visualise.css
  app/templates/base.html
  app/templates/home.html
  app/utilities/metadata.py
Labels: bug, enhancement, frontend, backend

#140 Update README.md
  README.md
Labels: documentation, enhancement

#142 Prevent Hover and Selection Export PDF
  app/routes.py
  app/static/js/visualise.js
Labels: bug, frontend, backend

#135 Issue 132 search bar filter
  app/static/js/home.js
  app/static/styles/home.css
Labels: frontend

#139 Duplicate File Name Handling
  app/static/js/home.js
Labels: bug, frontend

#144 File Upload Limits Adjustment
  app/config.py
  app/forms.py
  app/helper.py
  app/routes.py
Labels: enhancement, backend

#160 added performance test summary
  test/README_test.md
  test/performancetest/loacl_user_10.html
  test/performancetest/summary/Screenshot 2024-10-13 140316.png
  test/performancetest/summary/Screenshot 2024-10-13 140820.png
  test/performancetest/summary/Screenshot 2024-10-13 151953.png
  test/performancetest/summary/test_summary.md
Labels: documentation

#159 Team Page Design
  README.md
  app/config.py
  app/static/styles/visualise.css
  app/templates/team.html
Labels: enhancement, frontend
