Repository normit581/cits3200-proj, pull requests merged in 2024-09, with the labels that each got.

#56 set default height 700 to adjust height input
  app/static/js/visualise.js
  app/static/styles/base.css
  app/static/styles/visualise.css
  app/templates/visualise.html
Labels: enhancement, frontend

#57 Issue 49 rsid section color on visualise page
  app/static/js/visualise.js
  app/static/styles/base.css
  app/static/styles/visualise.css
  app/templates/visualise.html
  app/utilities/metadata.py
Labels: enhancement, frontend

#63 Issue 59 change setting bar to context menu
  app/static/js/context-menu.js
  app/static/js/home.js
  app/static/js/setting-bar.js
  app/static/js/visualise.js
  app/static/styles/base.css
  app/static/styles/visualise.css
  app/templates/home.html
  app/templates/visualise.html
Labels: bug, enhancement, frontend

#60 Issue 58 add warning for duplicate file names
  app/static/js/home.js
Labels: bug, frontend

#72 Issue 65 color picker with rsid synchronisation
  app/helper.py
  app/routes.py
  app/static/js/colour.js
  app/static/js/visualise.js
  app/static/styles/visualise.css
  app/templates/home.html
  app/templates/visualise.html
  app/utilities/metadata.py
Labels: bug, enhancement, frontend, backend

#78 bug fix filename BE FE
  app/routes.py
  app/static/js/home.js
Labels: bug, backend

#83 border colour docx card Match result
  app/static/js/home.js
Labels: enhancement, frontend

#80 rsid tooltip display, export pdf
  app/static/js/visualise.js
  app/static/styles/visualise.css
  app/templates/visualise.html
Labels: frontend

#84 bug fix error message display return from BE
  app/helper.py
  app/routes.py
  app/static/js/home.js
Labels: bug, backend

#85 Issue 54 minimum percentage match filter
  app/static/js/home.js
  app/static/styles/base.css
  app/templates/home.html
  app/templates/visualise.html
Labels: frontend

#88 Running Docker on Windows
  requirements.txt
  run.md
Labels: documentation

#93 User Stories for next sprint
  documents/sprint2_deliverables/CITS3200 User Stories.docx
Labels: documentation

#87 bug fix and ui improvement
  app/static/js/visualise.js
  app/templates/home.html
Labels: bug, frontend

#96 Issue 95 bootstrap tooltip to tippy js
  app/static/js/visualise.js
  app/static/styles/visualise.css
  app/templates/visualise.html
Labels: enhancement, frontend

#97 Issue 94 overlay to prevent multiple requests on submit
  app/routes.py
  app/static/js/home.js
  app/static/js/progress-overlay.js
  app/templates/home.html
  app/templates/layout/progress_overlay.html
Labels: enhancement, frontend

#99 Issue 98 fix alignment and excessive render
  app/static/js/visualise.js
  app/static/styles/visualise.css
Labels: bug, enhancement, frontend

#104 Issue 102 overlay visualise page
  app/routes.py
  app/static/js/home.js
  app/static/js/progress-overlay.js
  app/static/js/visualise.js
  app/templates/visualise.html
Labels: bug, enhancement, frontend, backend

#107 add bottom border to the selected text RSIDs
  app/static/js/visualise.js
  app/static/styles/visualise.css
Labels: enhancement, frontend

#117 adjust css
  app/static/styles/visualise.css
Labels: enhancement, frontend

#119 prevent upload only 1 file
  app/forms.py
  app/helper.py
Labels: bug, backend

#112 temporarily hide tooltip during overlay process
  app/static/js/visualise.js
  app/static/styles/visualise.css
Labels: bug, frontend

#116 remove duplicates more as possible
  app/helper.py
  app/routes.py
Labels: enhancement, backend
